package com.isoft.dls.domain.enumeration;

/**
 * The PhaseType enumeration.
 */
public enum PhaseType {
    CUSTOMER_ELIGIBILITY, DRIVING_LEARNING_FILE_PROCESSING, DRIVING_LEARNING_FILE_AUDIT, READY_FOR_CONTRACT_SIGN, EYE_TEST, THEORY_LECTURE, KNOWLEDGE_TEST, PRACTICAL_TRAINING, YARD_TEST, ADVANCED_PRACTICAL_TRAINING, ROAD_TEST, PRINT_LICENSE, APPLICATION_REJECTION, EXEMPTION_AUDITING, GET_REQUEST_DETAILS, CREATE_USER_DELIVERY, HUMAN_TASK_APPROVAL
}
